version: "3.8"
services:
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./site:/var/www/html/site
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=nginx-test
      - NGINX_PORT=80
  phpfpm:
    image: php:7.4-fpm
    volumes:
      - ./site:/var/www/html/site
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456