version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080